# Generated by Django 5.1.1 on 2024-10-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_content_review_review_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_date']},
        ),
    ]
